model: "FasterSpeech"
sample_rate: &sample_rate 22050
n_mels: &n_mels 80
labels: [
  # Space
    ' ',
  # string.ascii_letters
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  # Punctuation
    ',', '.', '!', '?', ';', ':', '-', '/',
    '"', "'", '(', ')', '[', ']', '{', '}',
]

FasterSpeechDataLayer_train:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: true
    drop_last: true
    shuffle: true

FasterSpeechDataLayer_eval:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: true
    drop_last: false
    shuffle: false

AudioToMelSpectrogramPreprocessor:  # Full good-TTS config.
    sample_rate: *sample_rate
    window_size: null  # Because "n_window_size" below is set.
    window_stride: null  # Because "n_window_size" below is set.
    n_window_size: 1024
    n_window_stride: 256
    window: 'hann'
    normalize: null  # Seems like it's bad for TTS.
    n_fft: 1024
    preemph: null
    features: *n_mels  # 80 works good for TTS.
    lowfreq: 0
    highfreq: null
    log: true
    log_zero_guard_type: 'clamp'  # 'clamp' just seems more reasonable.
    log_zero_guard_value: 1e-05
    dither: 0.0
    pad_to: 16
    frame_splicing: 1
    stft_conv: true
    pad_value: -11.52
    mag_power: 1.0  # People use 1.0 for TTS for some reason.

LenSampler:
    max_len: 1100  # Max LJSpeech dur is 10.10sec, so it's never happens.

# QuartzNet15x5 without 2x First Stride and Jasper's kernel sizes
JasperEncoder:
    activation: "relu"
    conv_mask: true

    # (Number of Layers) x (Number of Filters) x (Kernel Size)
    jasper:
        # First Layers
        -   filters: 256
            repeat: 3  # First repeat is 1.
            kernel: [5]  # Was 33 in Original QuartzNet15x5 (here and further).
            stride: [1]  # Was 2 in Original QuartzNet15x5.
            dilation: [1]
            dropout: 0.0
            residual: true  # Non-Residual
            separable: true

        # 3 x 256 x 5
        -   filters: 256
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 5
        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 5
        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 1 x 512 x 5
        -   filters: 512
            repeat: 1
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true  # Non-Residual
            separable: true

        # Last Layer
        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false  # Non-Residual
